/machine_states/main_robot:
  ros__parameters:

    # Robot states 
    emergency: 0                # Index for EMERGENCY state 
    manual: 1                   # Index for MANUAL state 
    autonomous: 2               # Index for AUTONOMOUS state 
    in_goal: 3                  # Index for IN GOAL state 
    mission_completed: 4        # Index for MISSION COMPLETED state 
    
    # Debug/test 
    use_sim_time: false         # Use simulation time 
    debug: false                # Enable debug prints 